[2022-12-13 12:15:38,716] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:16:20,871] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:16:24,598] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:16:24,600] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:16:24,604] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:16:37,760] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [4.29, 127.0.0.1:50995]
[2022-12-13 12:16:38,101] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css 304 [0.06, 127.0.0.1:50995]
[2022-12-13 12:16:38,115] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap-tweaks.css 304 [0.06, 127.0.0.1:50998]
[2022-12-13 12:16:38,126] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/prettify.css 304 [0.07, 127.0.0.1:50999]
[2022-12-13 12:16:38,135] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/default.css 304 [0.07, 127.0.0.1:51000]
[2022-12-13 12:16:38,177] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/jquery-3.5.1.min.js 304 [0.11, 127.0.0.1:51001]
[2022-12-13 12:16:38,185] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/ajax-form.js 304 [0.11, 127.0.0.1:51002]
[2022-12-13 12:16:38,201] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/csrf.js 304 [0.09, 127.0.0.1:50995]
[2022-12-13 12:16:38,220] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/bootstrap.min.js 304 [0.02, 127.0.0.1:50998]
[2022-12-13 12:16:38,230] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/default.js 304 [0.02, 127.0.0.1:51000]
[2022-12-13 12:16:38,241] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/prettify-min.js 304 [0.03, 127.0.0.1:50999]
[2022-12-13 12:16:38,390] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/img/grid.png 304 [0.01, 127.0.0.1:50999]
[2022-12-13 12:16:38,630] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 304 [0.04, 127.0.0.1:50999]
[2022-12-13 12:16:39,480] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:16:39,484] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.17, 127.0.0.1:50999]
[2022-12-13 12:16:39,623] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-12-13 12:16:39,623] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /favicon.ico 404 [0.07, 127.0.0.1:50999]
[2022-12-13 12:16:52,289] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.28, 127.0.0.1:51013]
[2022-12-13 12:16:52,613] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:16:52,617] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.09, 127.0.0.1:51017]
[2022-12-13 12:18:42,911] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:18:43,909] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:18:43,909] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:18:43,909] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:18:45,046] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.65, 127.0.0.1:51093]
[2022-12-13 12:18:47,405] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.24, 127.0.0.1:51093]
[2022-12-13 12:18:51,224] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:18:51,229] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.17, 127.0.0.1:51099]
[2022-12-13 12:20:21,222] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.43, 127.0.0.1:51143]
[2022-12-13 12:20:23,567] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:20:23,571] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.09, 127.0.0.1:51145]
[2022-12-13 12:20:45,622] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.51, 127.0.0.1:51156]
[2022-12-13 12:20:45,944] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:20:45,951] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.12, 127.0.0.1:51156]
[2022-12-13 12:24:45,354] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:24:46,305] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:24:46,305] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:24:46,321] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:24:51,335] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.57, 127.0.0.1:51287]
[2022-12-13 12:24:53,969] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:24:53,973] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.09, 127.0.0.1:51287]
[2022-12-13 12:36:30,688] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:36:31,777] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:36:31,779] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:36:31,784] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:37:24,168] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:37:25,136] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:37:25,136] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:37:25,136] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:37:37,630] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.75, 127.0.0.1:51669]
[2022-12-13 12:37:42,143] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:37:42,146] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.20, 127.0.0.1:51673]
[2022-12-13 12:37:49,715] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/15 200 [4.67, 127.0.0.1:51676]
[2022-12-13 12:38:10,097] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 12:38:19,409] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:38:20,379] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:38:20,395] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:38:20,395] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:39:07,353] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 12:39:14,762] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:39:15,715] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:39:15,715] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:39:15,715] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:39:23,101] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 12:39:30,439] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:41:42,962] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:41:43,945] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:41:43,961] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:41:43,961] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:42:06,696] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 12:42:15,778] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:42:16,790] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:42:16,791] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:42:16,796] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:42:21,010] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.57, 127.0.0.1:51816]
[2022-12-13 12:42:24,038] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:42:24,042] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.10, 127.0.0.1:51816]
[2022-12-13 12:42:52,444] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/15
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 536, in put
    relation_current.clear()
AttributeError: 'QuerySet' object has no attribute 'clear'
[2022-12-13 12:42:52,475] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/15 500 [7.42, 127.0.0.1:51832]
[2022-12-13 12:43:18,955] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:43:19,938] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:43:19,938] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:43:19,938] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:43:26,502] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:43:26,507] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.17, 127.0.0.1:51871]
[2022-12-13 12:44:41,278] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/15
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 536, in put
    relation_current.clear()
AttributeError: 'QuerySet' object has no attribute 'clear'
[2022-12-13 12:44:41,294] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/15 500 [72.98, 127.0.0.1:51871]
[2022-12-13 12:45:37,189] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:45:37,577] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:45:37,577] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:45:37,577] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:45:45,096] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.19, 127.0.0.1:51954]
[2022-12-13 12:45:45,266] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:45:45,268] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.04, 127.0.0.1:51954]
[2022-12-13 12:45:56,340] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /relations/ 200 [0.30, 127.0.0.1:51965]
[2022-12-13 12:45:56,501] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:45:56,503] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.04, 127.0.0.1:51965]
[2022-12-13 12:45:58,674] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.09, 127.0.0.1:51965]
[2022-12-13 12:45:58,856] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:45:58,858] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:51965]
[2022-12-13 12:46:15,132] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.09, 127.0.0.1:51977]
[2022-12-13 12:46:15,334] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:46:15,336] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:51977]
[2022-12-13 12:46:25,654] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/15
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 514, in put
    relateds = datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-13 12:46:25,665] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/15 500 [0.15, 127.0.0.1:51988]
[2022-12-13 12:47:08,464] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.07, 127.0.0.1:52007]
[2022-12-13 12:47:08,630] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:47:08,632] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.04, 127.0.0.1:52007]
[2022-12-13 12:47:12,774] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.08, 127.0.0.1:52013]
[2022-12-13 12:47:12,977] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:47:12,978] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52013]
[2022-12-13 12:47:32,910] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:47:33,861] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:47:33,861] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:47:33,861] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:47:36,960] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.55, 127.0.0.1:52045]
[2022-12-13 12:47:37,195] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:47:37,199] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.10, 127.0.0.1:52045]
[2022-12-13 12:48:47,518] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/15 200 [64.88, 127.0.0.1:52050]
[2022-12-13 12:48:54,146] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.23, 127.0.0.1:52050]
[2022-12-13 12:48:54,376] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:48:54,381] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.10, 127.0.0.1:52050]
[2022-12-13 12:48:58,464] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.33, 127.0.0.1:52088]
[2022-12-13 12:48:58,671] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:48:58,676] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.08, 127.0.0.1:52088]
[2022-12-13 12:51:03,520] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:51:03,879] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:51:03,879] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:51:03,895] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:52:09,630] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 12:52:12,488] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 12:52:12,909] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 12:52:12,909] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 12:52:12,909] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 12:53:23,356] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.18, 127.0.0.1:52222]
[2022-12-13 12:53:23,514] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:53:23,515] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:52222]
[2022-12-13 12:53:29,027] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.07, 127.0.0.1:52229]
[2022-12-13 12:53:29,208] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:53:29,210] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52229]
[2022-12-13 12:53:38,700] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/15 200 [0.06, 127.0.0.1:52238]
[2022-12-13 12:53:59,245] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/6 200 [0.08, 127.0.0.1:52253]
[2022-12-13 12:54:01,903] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:54:01,905] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52257]
[2022-12-13 12:54:42,851] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/15 200 [0.07, 127.0.0.1:52273]
[2022-12-13 12:55:01,309] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.07, 127.0.0.1:52281]
[2022-12-13 12:55:01,431] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:55:01,433] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52281]
[2022-12-13 12:55:38,770] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/15 200 [0.11, 127.0.0.1:52301]
[2022-12-13 12:55:44,084] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.09, 127.0.0.1:52301]
[2022-12-13 12:55:44,264] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:55:44,265] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52301]
[2022-12-13 12:55:50,917] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.08, 127.0.0.1:52310]
[2022-12-13 12:55:51,102] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:55:51,103] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:52310]
[2022-12-13 12:56:34,311] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/15 200 [0.09, 127.0.0.1:52328]
[2022-12-13 12:56:34,464] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 12:56:34,466] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52328]
[2022-12-13 12:56:44,298] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/15 200 [0.17, 127.0.0.1:52334]
[2022-12-13 12:56:49,711] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.09, 127.0.0.1:52339]
[2022-12-13 12:56:49,851] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 12:56:49,853] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:52339]
[2022-12-13 13:14:28,012] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.07, 127.0.0.1:52790]
[2022-12-13 13:14:29,632] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 13:14:29,633] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:52790]
[2022-12-13 13:14:37,897] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/6 200 [0.08, 127.0.0.1:52805]
[2022-12-13 13:14:38,735] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:14:38,738] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52805]
[2022-12-13 13:14:50,386] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/6
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 556, in delete
    return Response(dict(self.get_serializer(pro).data, **{"msg": '删除成功'}))
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 684, in to_representation
    iterable = data.all() if isinstance(data, models.Manager) else data
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\manager.py", line 164, in all
    return self.get_queryset()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\fields\related_descriptors.py", line 689, in get_queryset
    raise ValueError(
ValueError: 'casenew' instance needs to have a primary key value before this relationship can be used.
[2022-12-13 13:14:50,386] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP DELETE /cases/6 500 [0.39, 127.0.0.1:52811]
[2022-12-13 13:15:01,577] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.07, 127.0.0.1:52819]
[2022-12-13 13:15:01,736] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 13:15:01,738] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:52819]
[2022-12-13 13:15:10,241] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/6
[2022-12-13 13:15:10,243] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/6 404 [0.07, 127.0.0.1:52829]
[2022-12-13 13:15:10,411] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:15:10,413] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52829]
[2022-12-13 13:15:40,366] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 13:15:43,318] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 13:15:43,709] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 13:15:43,711] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 13:15:43,713] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 13:15:44,004] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.29, 127.0.0.1:52852]
[2022-12-13 13:15:50,469] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:15:50,472] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.05, 127.0.0.1:52859]
[2022-12-13 13:15:55,053] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/2 200 [0.08, 127.0.0.1:52868]
[2022-12-13 13:15:55,209] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:15:55,212] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52868]
[2022-12-13 13:15:57,279] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/2 200 [0.07, 127.0.0.1:52868]
[2022-12-13 13:16:03,862] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:52876]
[2022-12-13 13:16:07,443] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:52876]
[2022-12-13 13:16:07,613] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:16:07,615] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52876]
[2022-12-13 13:16:09,187] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.08, 127.0.0.1:52884]
[2022-12-13 13:16:09,373] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 13:16:09,374] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:52884]
[2022-12-13 13:16:17,045] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /relations/ 200 [0.09, 127.0.0.1:52891]
[2022-12-13 13:16:17,171] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 13:16:17,173] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:52891]
[2022-12-13 13:16:22,193] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:52895]
[2022-12-13 13:16:22,383] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:16:22,385] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52895]
[2022-12-13 13:16:29,167] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/4 200 [0.10, 127.0.0.1:52903]
[2022-12-13 13:16:29,370] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:16:29,371] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52903]
[2022-12-13 13:16:31,587] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/4 200 [0.10, 127.0.0.1:52903]
[2022-12-13 13:16:34,420] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.06, 127.0.0.1:52907]
[2022-12-13 13:16:34,595] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 13:16:34,598] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.04, 127.0.0.1:52907]
[2022-12-13 13:17:00,933] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /relations/ 200 [0.12, 127.0.0.1:52920]
[2022-12-13 13:17:01,138] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-13 13:17:01,140] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:52920]
[2022-12-13 13:17:08,659] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/8 200 [0.08, 127.0.0.1:52924]
[2022-12-13 13:17:08,830] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:17:08,832] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52924]
[2022-12-13 13:17:30,686] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:52934]
[2022-12-13 13:17:33,190] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:17:33,192] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52939]
[2022-12-13 13:18:27,719] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:52960]
[2022-12-13 13:18:30,143] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:18:30,145] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:52962]
[2022-12-13 13:18:40,419] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.10, 127.0.0.1:52971]
[2022-12-13 13:18:45,426] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/18 200 [0.08, 127.0.0.1:52975]
[2022-12-13 13:18:45,575] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:18:45,578] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52975]
[2022-12-13 13:18:52,627] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:52979]
[2022-12-13 13:18:52,842] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:18:52,844] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52979]
[2022-12-13 13:19:13,491] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.09, 127.0.0.1:52992]
[2022-12-13 13:19:19,501] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/19 200 [0.08, 127.0.0.1:53000]
[2022-12-13 13:19:19,655] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:19:19,656] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:53000]
[2022-12-13 13:19:34,928] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:53007]
[2022-12-13 13:19:41,027] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:19:41,028] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:53013]
[2022-12-13 13:19:51,436] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 424, in post
    relateds=datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-13 13:19:51,446] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /cases/ 500 [0.13, 127.0.0.1:53018]
[2022-12-13 13:19:51,797] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:19:51,801] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:53018]
[2022-12-13 13:27:37,314] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\models.py changed, reloading.
[2022-12-13 13:27:54,190] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 13:28:42,749] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\models.py changed, reloading.
[2022-12-13 13:28:44,619] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 13:29:45,144] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\models.py changed, reloading.
[2022-12-13 13:30:01,905] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 13:30:07,099] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 13:30:07,131] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 13:30:07,131] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 13:31:23,961] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 13:31:24,460] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 13:31:24,460] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 13:31:24,460] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 13:33:15,196] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [9.24, 127.0.0.1:53331]
[2022-12-13 13:33:22,555] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 13:33:22,556] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.75, 127.0.0.1:53343]
[2022-12-13 13:33:23,025] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-12-13 13:33:23,025] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /favicon.ico 404 [0.03, 127.0.0.1:53343]
[2022-12-13 13:34:20,397] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 13:36:49,618] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 13:37:06,295] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 13:37:06,326] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 13:37:06,326] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 14:36:11,644] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.87, 127.0.0.1:53876]
[2022-12-13 14:37:02,803] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.61, 127.0.0.1:53900]
[2022-12-13 14:38:06,783] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.20, 127.0.0.1:53921]
[2022-12-13 14:38:43,746] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 14:38:43,747] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [2.34, 127.0.0.1:53943]
[2022-12-13 14:38:47,525] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [23.00, 127.0.0.1:53932]
[2022-12-13 14:38:48,480] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/css/base.css 304 [0.09, 127.0.0.1:53932]
[2022-12-13 14:38:48,484] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/css/dark_mode.css 304 [0.10, 127.0.0.1:53948]
[2022-12-13 14:38:48,686] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/css/nav_sidebar.css 304 [0.29, 127.0.0.1:53949]
[2022-12-13 14:38:48,757] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/css/responsive.css 304 [0.33, 127.0.0.1:53950]
[2022-12-13 14:38:48,984] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/nav_sidebar.js 304 [0.54, 127.0.0.1:53951]
[2022-12-13 14:38:48,992] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/css/fonts.css 304 [0.13, 127.0.0.1:53950]
[2022-12-13 14:38:49,428] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/img/icon-addlink.svg 304 [0.23, 127.0.0.1:53952]
[2022-12-13 14:38:50,529] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 304 [0.09, 127.0.0.1:53952]
[2022-12-13 14:38:50,533] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 304 [0.09, 127.0.0.1:53953]
[2022-12-13 14:38:50,537] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 304 [0.09, 127.0.0.1:53954]
[2022-12-13 14:38:51,369] [log.py:241] [log:log_response] [WARNING]- Not Found: /admin/jquery.min.js
[2022-12-13 14:38:51,370] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /admin/jquery.min.js 404 [0.45, 127.0.0.1:53954]
[2022-12-13 14:38:55,775] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/ 200 [1.85, 127.0.0.1:53954]
[2022-12-13 14:38:56,821] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/css/changelists.css 304 [0.00, 127.0.0.1:53954]
[2022-12-13 14:38:56,948] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/vendor/jquery/jquery.js 304 [0.10, 127.0.0.1:53958]
[2022-12-13 14:38:57,028] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/admin/RelatedObjectLookups.js 304 [0.18, 127.0.0.1:53954]
[2022-12-13 14:38:57,036] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/core.js 304 [0.19, 127.0.0.1:53960]
[2022-12-13 14:38:57,040] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/jquery.init.js 304 [0.19, 127.0.0.1:53959]
[2022-12-13 14:38:57,120] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/actions.js 304 [0.27, 127.0.0.1:53961]
[2022-12-13 14:38:57,125] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/urlify.js 304 [0.01, 127.0.0.1:53958]
[2022-12-13 14:38:57,129] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/prepopulate.js 304 [0.01, 127.0.0.1:53954]
[2022-12-13 14:38:57,415] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/vendor/xregexp/xregexp.js 304 [0.30, 127.0.0.1:53960]
[2022-12-13 14:38:57,884] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [1.04, 127.0.0.1:53957]
[2022-12-13 14:38:57,997] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/filters.js 304 [0.01, 127.0.0.1:53957]
[2022-12-13 14:38:58,347] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/img/search.svg 304 [0.35, 127.0.0.1:53960]
[2022-12-13 14:38:58,439] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/admin/img/tooltag-add.svg 304 [0.06, 127.0.0.1:53960]
[2022-12-13 14:39:01,826] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/jquery.min.js/ 302 [0.44, 127.0.0.1:53967]
[2022-12-13 14:39:02,636] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/jquery.min.js/change/ 302 [0.81, 127.0.0.1:53967]
[2022-12-13 14:39:03,136] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.50, 127.0.0.1:53967]
[2022-12-13 14:39:39,668] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:53992]
[2022-12-13 14:39:55,797] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.12, 127.0.0.1:54010]
[2022-12-13 14:40:38,432] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.19, 127.0.0.1:54039]
[2022-12-13 14:41:05,876] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.18, 127.0.0.1:54056]
[2022-12-13 14:41:57,830] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.19, 127.0.0.1:54082]
[2022-12-13 14:42:20,740] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.12, 127.0.0.1:54098]
[2022-12-13 14:42:27,498] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:54108]
[2022-12-13 14:42:32,163] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.11, 127.0.0.1:54119]
[2022-12-13 14:42:38,032] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:54126]
[2022-12-13 14:43:55,585] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.14, 127.0.0.1:54164]
[2022-12-13 14:44:26,253] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:54182]
[2022-12-13 14:45:12,343] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.10, 127.0.0.1:54211]
[2022-12-13 14:45:22,008] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.06, 127.0.0.1:54219]
[2022-12-13 14:45:31,186] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.11, 127.0.0.1:54230]
[2022-12-13 14:45:39,406] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.05, 127.0.0.1:54239]
[2022-12-13 14:45:44,177] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.11, 127.0.0.1:54246]
[2022-12-13 14:46:17,037] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.06, 127.0.0.1:54263]
[2022-12-13 14:46:33,419] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:54273]
[2022-12-13 14:46:41,037] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.06, 127.0.0.1:54281]
[2022-12-13 14:46:47,013] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.05, 127.0.0.1:54290]
[2022-12-13 14:47:36,245] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:54318]
[2022-12-13 14:47:49,793] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:54328]
[2022-12-13 14:47:57,921] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=2 200 [0.09, 127.0.0.1:54340]
[2022-12-13 14:48:01,181] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=1 200 [0.06, 127.0.0.1:54346]
[2022-12-13 14:50:18,370] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.41, 127.0.0.1:54411]
[2022-12-13 14:50:48,534] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.30, 127.0.0.1:54428]
[2022-12-13 14:51:03,758] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:54444]
[2022-12-13 14:51:19,512] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:54457]
[2022-12-13 14:51:29,483] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:54467]
[2022-12-13 14:51:43,346] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=2 200 [0.08, 127.0.0.1:54479]
[2022-12-13 14:51:45,203] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=1 200 [0.09, 127.0.0.1:54483]
[2022-12-13 14:52:31,726] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:54506]
[2022-12-13 14:52:45,874] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=2 200 [0.09, 127.0.0.1:54520]
[2022-12-13 14:52:46,288] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=1 200 [0.08, 127.0.0.1:54523]
[2022-12-13 14:52:52,249] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:54535]
[2022-12-13 14:53:29,586] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:54558]
[2022-12-13 14:53:40,856] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.61, 127.0.0.1:54571]
[2022-12-13 14:53:48,767] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.27, 127.0.0.1:54586]
[2022-12-13 14:53:55,908] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.03, 127.0.0.1:54593]
[2022-12-13 14:53:57,003] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:54597]
[2022-12-13 14:54:08,536] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/17 200 [1.94, 127.0.0.1:54623]
[2022-12-13 14:54:08,536] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/14 200 [1.99, 127.0.0.1:54613]
[2022-12-13 14:54:08,536] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/16 200 [1.95, 127.0.0.1:54622]
[2022-12-13 14:54:08,536] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/18 200 [1.94, 127.0.0.1:54624]
[2022-12-13 14:54:08,552] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/15 200 [1.98, 127.0.0.1:54620]
[2022-12-13 14:54:08,552] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/19 200 [1.93, 127.0.0.1:54625]
[2022-12-13 14:54:09,168] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/21 200 [0.31, 127.0.0.1:54635]
[2022-12-13 14:54:09,199] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/20 200 [0.35, 127.0.0.1:54633]
[2022-12-13 14:54:15,617] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:54644]
[2022-12-13 14:54:16,388] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.10, 127.0.0.1:54647]
[2022-12-13 14:54:23,348] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/24 200 [0.16, 127.0.0.1:54665]
[2022-12-13 14:54:23,348] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/22 200 [0.17, 127.0.0.1:54663]
[2022-12-13 14:54:23,379] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/23 200 [0.20, 127.0.0.1:54664]
[2022-12-13 14:54:23,486] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/27 200 [0.26, 127.0.0.1:54674]
[2022-12-13 14:54:23,488] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/25 200 [0.30, 127.0.0.1:54666]
[2022-12-13 14:54:23,491] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/26 200 [0.30, 127.0.0.1:54667]
[2022-12-13 14:54:23,804] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/28 200 [0.13, 127.0.0.1:54678]
[2022-12-13 14:54:25,665] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:54686]
[2022-12-13 14:54:25,999] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:54689]
[2022-12-13 14:54:29,683] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.03, 127.0.0.1:54696]
[2022-12-13 14:54:31,487] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:54702]
[2022-12-13 14:54:34,170] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:54706]
[2022-12-13 14:54:42,534] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/
[2022-12-13 14:54:42,534] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/?page=2 404 [0.09, 127.0.0.1:54714]
[2022-12-13 14:54:43,857] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=1 200 [0.07, 127.0.0.1:54717]
[2022-12-13 14:55:07,076] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:54734]
[2022-12-13 14:55:41,283] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/ 200 [0.59, 127.0.0.1:54753]
[2022-12-13 14:55:48,019] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.11, 127.0.0.1:54763]
[2022-12-13 14:55:49,395] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 14:55:49,397] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.07, 127.0.0.1:54763]
[2022-12-13 14:55:49,772] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/jquery.min.js/ 302 [0.37, 127.0.0.1:54763]
[2022-12-13 14:55:50,058] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/jquery.min.js/change/ 302 [0.28, 127.0.0.1:54763]
[2022-12-13 14:55:50,377] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.31, 127.0.0.1:54763]
[2022-12-13 14:56:13,390] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:54783]
[2022-12-13 14:56:16,371] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.12, 127.0.0.1:54790]
[2022-12-13 14:56:19,645] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=1 200 [0.11, 127.0.0.1:54799]
[2022-12-13 14:56:22,831] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?size=500 200 [0.13, 127.0.0.1:54806]
[2022-12-13 14:56:28,431] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?size=10 200 [0.21, 127.0.0.1:54815]
[2022-12-13 15:15:37,774] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 15:16:43,741] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 15:16:57,237] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 15:16:57,237] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 15:16:57,237] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 15:18:10,052] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 15:18:13,660] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 15:18:14,162] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 15:18:14,162] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 15:18:14,162] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 15:19:59,263] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 15:21:27,160] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 15:21:29,391] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 15:21:29,391] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 15:21:29,391] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 15:21:53,265] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 454, in get
    case["method"] = self.get_get_serializer(data=case).get_method_display()
AttributeError: 'caseList' object has no attribute 'get_get_serializer'
[2022-12-13 15:21:53,300] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [9.14, 127.0.0.1:55691]
[2022-12-13 15:21:54,410] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 15:21:54,412] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.08, 127.0.0.1:55691]
[2022-12-13 15:22:41,806] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 15:23:01,824] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 15:23:05,272] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 15:23:05,272] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 15:23:05,274] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 15:23:11,332] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 454, in get
    case["method"] = self.get_serializer(data=case).get_method_display()
AttributeError: 'CaseModelSerializer' object has no attribute 'get_method_display'
[2022-12-13 15:23:11,344] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [2.43, 127.0.0.1:55749]
[2022-12-13 15:23:15,954] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 15:23:15,956] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:55757]
[2022-12-13 20:31:24,896] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-13 20:32:04,193] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 20:32:11,931] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 20:32:11,931] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 20:32:11,931] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 20:32:25,238] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-13 20:32:28,314] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 20:32:28,920] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 20:32:28,920] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 20:32:28,920] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 20:32:59,142] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:32:59,144] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.49, 127.0.0.1:57903]
[2022-12-13 20:33:03,996] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 454, in get
    case["method"] = self.get_serializer(data=case).get_method_display()
AttributeError: 'CaseModelSerializer' object has no attribute 'get_method_display'
[2022-12-13 20:33:04,008] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [1.37, 127.0.0.1:57906]
[2022-12-13 20:33:04,270] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:33:04,273] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.06, 127.0.0.1:57906]
[2022-12-13 20:33:14,248] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-13 20:33:18,052] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 20:33:18,536] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 20:33:18,536] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 20:33:18,536] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 20:33:24,796] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.15, 127.0.0.1:57921]
[2022-12-13 20:33:26,666] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:33:26,668] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.05, 127.0.0.1:57930]
[2022-12-13 20:33:59,907] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 20:34:00,516] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 20:34:00,516] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 20:34:00,531] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 20:34:03,924] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.48, 127.0.0.1:57958]
[2022-12-13 20:34:04,227] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:34:04,229] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:57958]
[2022-12-13 20:34:22,939] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 20:34:23,423] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 20:34:23,423] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 20:34:23,423] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 20:34:27,272] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.49, 127.0.0.1:57983]
[2022-12-13 20:34:27,626] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:34:27,628] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.14, 127.0.0.1:57983]
[2022-12-13 20:34:31,136] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.45, 127.0.0.1:57983]
[2022-12-13 20:34:31,353] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:34:31,355] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:57983]
[2022-12-13 20:39:00,167] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-13 20:39:23,117] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 20:39:26,668] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 20:39:26,668] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 20:39:26,668] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 20:39:32,093] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [5.14, 127.0.0.1:58355]
[2022-12-13 20:39:36,371] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:39:36,374] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.23, 127.0.0.1:58359]
[2022-12-13 20:48:51,730] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 20:48:54,448] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 20:48:54,449] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 20:48:54,452] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 20:48:55,773] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.88, 127.0.0.1:58748]
[2022-12-13 20:48:56,202] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:48:56,204] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.14, 127.0.0.1:58748]
[2022-12-13 20:50:20,869] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [2.44, 127.0.0.1:58806]
[2022-12-13 20:53:36,091] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [1.86, 127.0.0.1:58913]
[2022-12-13 20:53:36,588] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=1 200 [1.71, 127.0.0.1:58915]
[2022-12-13 20:58:59,302] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.47, 127.0.0.1:59054]
[2022-12-13 20:58:59,634] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 20:58:59,635] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.06, 127.0.0.1:59054]
[2022-12-13 20:59:47,813] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [1.67, 127.0.0.1:59111]
[2022-12-13 21:00:11,221] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.33, 127.0.0.1:59120]
[2022-12-13 21:00:19,133] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.29, 127.0.0.1:59124]
[2022-12-13 21:00:19,314] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 21:00:19,316] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:59124]
[2022-12-13 21:01:07,008] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.38, 127.0.0.1:59150]
[2022-12-13 21:07:23,438] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-13 21:08:22,129] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 21:09:08,053] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 21:09:08,138] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 21:09:08,140] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 21:10:09,192] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.47, 127.0.0.1:59678]
[2022-12-13 21:10:17,007] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-13 21:10:17,008] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.59, 127.0.0.1:59684]
[2022-12-13 21:10:46,722] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.42, 127.0.0.1:59697]
[2022-12-13 21:11:06,112] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.40, 127.0.0.1:59706]
[2022-12-13 21:18:40,583] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-13 21:18:50,649] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-13 21:18:50,649] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-13 21:18:50,649] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-13 21:22:13,811] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/ 200 [24.22, 127.0.0.1:60454]
[2022-12-13 21:22:14,205] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [6.20, 127.0.0.1:60494]
[2022-12-13 21:22:16,855] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [1.52, 127.0.0.1:60454]
[2022-12-13 21:22:22,378] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/jquery.min.js/ 302 [0.53, 127.0.0.1:60519]
[2022-12-13 21:22:23,524] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /admin/saas/casenew/jquery.min.js/change/ 302 [1.14, 127.0.0.1:60519]
[2022-12-13 21:22:27,389] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [3.80, 127.0.0.1:60519]
[2022-12-13 21:22:29,989] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.86, 127.0.0.1:60535]
[2022-12-13 21:23:14,013] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
